# Generated by Django 5.2.1 on 2025-05-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_parent_mother_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='premanent_address',
            new_name='permanent_address',
        ),
    ]
